sensor_msgs/PointCloud2 known_free
sensor_msgs/PointCloud2[] chss
int32 num_samples
---
sensor_msgs/PointCloud2[] sampled_completions
#gpu_voxel_planning_msgs/JointConfig[] goal_configs
gpu_voxel_planning_msgs/TSR[] goal_tsrs